#ifndef __PURGE_VERSION_GENERATED_H
#define __PURGE_VERSION_GENERATED_H

#define PURGE_FW_GIT_SHA "g2d87aa97"
#define PURGE_FW_BUILD_TIME "2026-04-28 13:37:00"

#endif /* __PURGE_VERSION_GENERATED_H */