#ifndef __PURGE_VERSION_GENERATED_H
#define __PURGE_VERSION_GENERATED_H

#define PURGE_FW_GIT_SHA "gb6e0555d-dirty"
#define PURGE_FW_BUILD_TIME "2026-04-17 14:42:35"

#endif /* __PURGE_VERSION_GENERATED_H */