#ifndef __PURGE_VERSION_GENERATED_H
#define __PURGE_VERSION_GENERATED_H

#define PURGE_FW_GIT_SHA "gb072886b"
#define PURGE_FW_BUILD_TIME "2026-04-17 15:09:45"

#endif /* __PURGE_VERSION_GENERATED_H */